const views=document.querySelectorAll('.view');const navItems=document.querySelectorAll('.nav-item');
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));const navView=id==='limpieza'?'programacion':id;navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===navView));document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}navItems.forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
const modal=document.getElementById('modalBackdrop');const openModal=()=>modal.classList.add('show');const closeModal=()=>modal.classList.remove('show');document.getElementById('newPaymentBtn').onclick=openModal;document.getElementById('modalClose').onclick=closeModal;document.getElementById('cancelModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
const toast=document.getElementById('toast');function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
document.getElementById('paymentForm').addEventListener('submit',e=>{e.preventDefault();closeModal();notify('Pago registrado correctamente');e.target.reset()});
const payments=[{request:'SF-2026-0183',name:'CFE · Chihuahua',date:'22 jul 2026',amount:42650,var:'+8%',status:'Listo'},{request:'SF-2026-0183',name:'Internet · Juárez',date:'21 jul 2026',amount:8920,var:'+22%',status:'Variación'},{request:'SF-2026-0183',name:'Agua · Parral',date:'23 jul 2026',amount:5480,var:'-2%',status:'Listo'},{request:'SF-2026-0183',name:'Limpieza · Delicias',date:'25 jul 2026',amount:19380,var:'+4%',status:'Listo'},{request:'SF-2026-0181',name:'Internet · Chihuahua',date:'27 jul 2026',amount:6240,var:'+1%',status:'Falta recibo'},{request:'SF-2026-0180',name:'CFE · Parral',date:'29 jul 2026',amount:33860,var:'+12%',status:'Variación'}];
function renderPayments(){const tbody=document.getElementById('paymentsTable');tbody.innerHTML=payments.map((p,i)=>{const paid=p.status==='Pagado';const statusClass=paid||p.status==='Listo'?'approved':p.status==='Variación'?'waiting':'rejected';return `<tr class="${paid?'payment-completed':''}"><td><strong>${p.request||'—'}</strong></td><td><strong>${p.name}</strong></td><td>${p.date}</td><td><strong>$${p.amount.toLocaleString('es-MX')}</strong></td><td><span class="${p.var.startsWith('+')?'orange-text':''}">${p.var}</span></td><td><span class="status ${statusClass}">${p.status}</span></td><td><button class="pay-row-btn" type="button" data-index="${i}" ${paid?'disabled':''}>${paid?'Pagado ✓':'Pagar'}</button></td><td><button class="more-btn" type="button" aria-label="Ver detalle">•••</button></td></tr>`}).join('')}renderPayments();
const days=['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'];let cells=days.map(d=>`<div class="calendar-day head">${d}</div>`);for(let blank=0;blank<3;blank++)cells.push('<div class="calendar-day calendar-empty" aria-hidden="true"></div>');for(let i=1;i<=31;i++){let events='';if(i===21)events='<button class="calendar-event orange" type="button" data-calendar-day="21"><b>09:30</b> Internet · Juárez</button>';if(i===22)events='<button class="calendar-event red" type="button" data-calendar-day="22"><b>12:00</b> CFE · Chihuahua</button>';if(i===23)events='<button class="calendar-event" type="button" data-calendar-day="23"><b>10:15</b> Agua · Parral</button>';if(i===25)events='<button class="calendar-event green" type="button" data-calendar-day="25"><b>16:00</b> Limpieza · 6 sucursales</button>';if(i===29)events='<button class="calendar-event orange" type="button" data-calendar-day="29"><b>11:00</b> CFE · Parral</button>';cells.push(`<div class="calendar-day ${i===21?'calendar-today':''}"><span class="num">${i}</span>${events}</div>`)}document.getElementById('calendarGrid').innerHTML=cells.join('');
const week=['Lun 20','Mar 21','Mié 22','Jue 23','Vie 24','Sáb 25','Dom 26'];document.getElementById('weekChecks').innerHTML=week.map((d,i)=>`<label class="day-check ${i<5?'active':''}"><input type="checkbox" ${i<5?'checked':''}><span>${d.split(' ')[0]}</span><strong>${d.split(' ')[1]}</strong></label>`).join('');
function calcCleaning(){const active=[...document.querySelectorAll('.day-check input')].filter(i=>i.checked).length;const extra=Number(document.getElementById('extraDays').value||0);const discount=Number(document.getElementById('discount').value||0);const total=active*650+extra*650-discount;document.getElementById('workedDays').textContent=active;document.getElementById('extraAmount').textContent='$'+(extra*650).toLocaleString('es-MX');document.getElementById('discountAmount').textContent='-$'+discount.toLocaleString('es-MX');document.getElementById('cleaningTotal').textContent='$'+total.toLocaleString('es-MX')}
document.querySelectorAll('.day-check').forEach(l=>l.addEventListener('click',()=>{setTimeout(()=>{l.classList.toggle('active',l.querySelector('input').checked);calcCleaning()},0)}));document.getElementById('extraDays').addEventListener('input',calcCleaning);document.getElementById('discount').addEventListener('input',calcCleaning);
document.querySelectorAll('.attention-item').forEach(item=>item.addEventListener('click',()=>{if(item.dataset.action==='go-programacion')showView('programacion');else notify('Detalle abierto en modo prototipo')}));
const pendingPanel=document.getElementById('pendingPanel');const notificationBtn=document.getElementById('notificationBtn');const closePending=()=>{pendingPanel.classList.remove('show');pendingPanel.setAttribute('aria-hidden','true')};notificationBtn.addEventListener('click',e=>{e.stopPropagation();const open=!pendingPanel.classList.contains('show');pendingPanel.classList.toggle('show',open);pendingPanel.setAttribute('aria-hidden',String(!open))});document.getElementById('closePending').addEventListener('click',closePending);document.querySelectorAll('[data-pending-view]').forEach(item=>item.addEventListener('click',()=>{showView(item.dataset.pendingView);closePending()}));document.addEventListener('click',e=>{if(!pendingPanel.contains(e.target)&&e.target!==notificationBtn)closePending()});
document.getElementById('globalSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(q.length>2){document.querySelectorAll('table tbody tr,.branch-card,.attention-item').forEach(el=>el.style.opacity=el.textContent.toLowerCase().includes(q)?'1':'.25')}else document.querySelectorAll('table tbody tr,.branch-card,.attention-item').forEach(el=>el.style.opacity='1')});
